#Paramètres du jeu
#Fri May 02 20:38:37 CEST 2025
fullscreen=true
langue=English
musicVolume=9
resolution=1280x720
sfxVolume=6
touches.moveDown=S
touches.moveLeft=A
touches.moveRight=D
touches.moveUp=W
